### ISSUE TITLE
Extension Issue

### ISSUE THREAD

**Issue by moshboaron** [Trolleymusic/mixitup-loadmore#4]
Hey,

I tried to implement your extension but I got this errors:
http://take.ms/5xids

Can you please help me to solve this issue?

Mosh

**Comment by rdennler** [comment]
Issue might be due to possibly loading the loadmore jQuery before mixitup and not after , since it uses .extend you'd want to go in this order:

**jQuery -> Mixitup -> Mixitup Loadmore extension library -> Call your mixitup object and define configuration** 

Hope this helps

**Comment by Trolleymusic** [comment]
Thanks @Ryan4021
